language: c

sudo: required
dist: trusty

services:
  - docker
  - postgresql

before_install:
- docker pull spotify/kafka
- docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=127.0.0.1 --env ADVERTISED_PORT=9092 spotify/kafka
- docker ps -a
- sudo apt-get install -qq librdkafka1 kafkacat
- echo "test message" | kafkacat -P -b 127.0.0.1:9092  -t test
- kafkacat -C -b 127.0.0.1:9092  -t test -p 0 -c 1

script: make && make installcheck

compiler:
  - clang
  - gcc

env:
  global:
  - USE_PGXS=1
